version: '3.7'

services:
  backend_prod:
    container_name: BackendProd_23_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '15556:8080'
    volumes:
      - backend_prod_logs_23_1:/code/logs

volumes:
  backend_prod_logs_23_1:
